- name: "Verify presence of an old ca certificate"
  stat:
    path: /etc/vault.d/tls/vault-ca.pem
  register: tls_ca
  tags:
    - tls

- name: "Verify presence of an old server certificate"
  stat:
    path: "/etc/vault.d/tls/server.pem"
  register: tls_srv
  tags:
    - tls

- name: "Verify presence of an old server key"
  stat:
    path: "/etc/vault.d/tls/server.key.pem"
  register: tls_srv_key
  tags:
    - tls

- name: "Purge old config files"
  file:
    state: absent
    path: "{{ role_path }}/files/tls"
  delegate_to: localhost
  run_once: true

- name: "Create local temporary path"
  file:
    state: directory
    path: "{{ role_path }}/files/tls"
  delegate_to: localhost
  run_once: true

- name: "Generate cfssl config files"
  lineinfile:
    create: yes
    path: "{{ role_path }}/files/tls/{{ item.path }}"
    line: "{{ item.line | to_nice_json }}"
  delegate_to: localhost
  run_once: true
  with_items:
    - path: "ca-config.json"
      line: "{{ cfssl.config }}"
    - path: "ca-csr.json"
      line: "{{ cfssl.csr.ca }}"

- name: "Generate cfssl config files for each server"
  lineinfile:
    create: yes
    path: "{{ role_path }}/files/tls/{{ item.path }}"
    line: "{{ item.line | to_nice_json }}"
  delegate_to: localhost
  with_items:
    - path: "server-{{ ansible_hostname }}.json"
      line: "{{ cfssl.csr.server }}"

- name: "Generate CA Certificate"
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
  args:
    chdir: "{{ role_path }}/files/tls"
  run_once: true
  delegate_to: localhost

- name: "Generate Server Certificate"
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server server-{{ ansible_hostname }}.json | cfssljson -bare server && mv server.pem {{ ansible_hostname }}-server.pem && mv server-key.pem {{ ansible_hostname }}-server-key.pem
  args:
    chdir: "{{ role_path }}/files/tls"
  delegate_to: localhost

- name: "Upload Certificates to server"
  copy:
    src: "tls/{{ ansible_hostname }}-{{ item }}"
    dest: "/etc/vault.d/tls/{{ item }}"
  notify: Restart Vault
  with_items:
    - server.pem
    - server-key.pem

