- name: "Upload CA certs"
  copy:
    src: "{{ vault_tls_ca_file }}"
    dest: "/etc/vault.d/tls/vault-ca.pem"
  when: vault_tls_ca_file is defined

- name: "Upload Server cert"
  copy:
    src: "{{ vault_tls_server_file }}"
    dest: "/etc/vault.d/tls/server.pem"
  when: vault_tls_server_file is defined

- name: "Upload Server key"
  copy:
    src: "{{ vault_tls_key_file }}"
    dest: "/etc/vault.d/tls/server.key.pem"
  when: vault_tls_server_file is defined
