- name: "Verify 'action' variable"
  fail:
    msg: "action must be on of [install|delete|restart]"
  when: action not in ('install','delete','restart')

- name: "Verify tls variables"
  fail:
    msg: "You cannot use both vault_tls_generate and vault_tls_provided"
  when: vault_use_tls and vault_tls_generate and vault_tls_provided

- include_tasks: "{{ action }}.yml"
  tags:
    - install
    - tls
    - configure
    - restart
